// ----------------------------------------------------------------------

export const role = [
  'Admin',
  'Organizer',
  'Admin',
  'Organizer',
  'Admin',
  'Organizer',
  'Admin',
  'Organizer',
  'Admin',
  'Organizer',
  'Admin',
  'Organizer',
  'Admin',
  'Organizer',
  'Admin',
  'Organizer',
  'Admin',
  'Organizer',
  'Admin',
  'Organizer',
  'Admin',
  'Organizer',
  'Admin',
  'Organizer',
];
